### PR TITLE
Adds CI to the repository

### PR DESCRIPTION
**Pull request by GToidZ**
This PR adds two CI workflows to:
* Code linting: we'll use flake8 to lint our code, this is to prevent our code style being unacceptable.
* Unit testing: this tests our unit tests and generate coverage reports (upload to Codecov soon.)

### CODE REVIEW

**Comment by GToidZ** [comment]
[CI: Integrate CI for Linting and Testing](https://trello.com/c/4cN7jWMI/27-ci-integrate-ci-for-linting-and-testing)

**Comment by GToidZ** [comment]
Checks are not needed to be all passing yet. We'll need to fix the source code later.

**Comment by Savetang19** [comment]
It looks okay 👍🏻

**Comment by GToidZ** [comment]
Alright, let's merge it then.

**Pull request merged**
