### PR TITLE
Add Bookmark button to frontend and bind it with backend

### PR DESCRIPTION
**Pull request by Savetang19**

### CODE REVIEW

**Review by GToidZ — APPROVED** [review]
Looks good! Merge approved krub.

**Comment by Tanabodee-Yambangyang** [comment]
Looks good!! Approve.

**Review by Supakrit65 — APPROVED** [review]
Those bookmark icons look iconic.

**Comment by Savetang19** [comment]
[Frontend: Bookmark button](https://trello.com/c/dSxVNwqT/39-frontend-bookmark-button)

**Pull request merged**
