### PR TITLE
Fix review datetime field

### PR DESCRIPTION
**Pull request by GToidZ**
This PR fixes naive datetime object that can and will happen in Film model. Purposing this change because Django's datetime adheres to the application's timezone.

### CODE REVIEW

**Comment by Savetang19** [comment]
Everything is OK 👍🏻

**Comment by Tanabodee-Yambangyang** [comment]
It's look good.

**Review by Supakrit65 — APPROVED** [review]
Agree

**Comment by GToidZ** [comment]
Okay, I'm merging this PR now.

**Comment by GToidZ** [comment]
I'm also deleting this branch since, it is minimal and having it on remote will clutter our workspace.

**Pull request merged**
