### PR TITLE
Implement Privacy Policy Page

### PR DESCRIPTION
**Pull request by Savetang19**
# What I have done in this PR?
- Add consent form and policy agreement after signup
- Add Privacy Policy section in profile page

### CODE REVIEW

**Review by JiratchayaPhinyodom — APPROVED** [review]
Approve

**Review by GToidZ — APPROVED** [review]
LGTM! Merge approved.

**Review by Tanabodee-Yambangyang — APPROVED** [review]
So good, merge approve quick!

**Review by Supakrit65 — APPROVED** [review]
Great work!

**Pull request merged**
