### PR TITLE
Adds feed to Fandom and more changes!

### PR DESCRIPTION
**Pull request by GToidZ**
# BREAKING CHANGES
* The migrations are deleted and revised, so it is **HIGHLY** recommended to all developers to reset their database. (Drop the `public` schema and rebuild it) Then, re-migrate for this application.
* The `requirements.txt` has been updated, you'd need to reinstall dependencies.

# Pull Request Summary
* Fandom names are now stripped of spaces and case-insensitive.
* Fandom lists reviews in their page which has a specific tag in the review content.
* Navigation is improved! Posting review button is now available.
* Anywhere that states date time is now end user local time.
* HTMX endpoints can only be invoked by HTMX requests only!

### CODE REVIEW

**Comment by Savetang19** [comment]
[Frontend: Fandom Page](https://trello.com/c/S20KWLnb/38-frontend-fandom-page)

**Comment by Savetang19** [comment]
[Frontend: Fandom Page](https://trello.com/c/S20KWLnb/38-frontend-fandom-page)

**Review by Savetang19 — APPROVED** [review]
I think everything is looking good! You can merged now!!!

**Review by Supakrit65 — APPROVED** [review]
Nice changes.

**Review by Tanabodee-Yambangyang — APPROVED** [review]
Look good!! You can merge now.

**Pull request merged**
